# Generated by Django 5.2 on 2025-05-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
