# Generated by Django 5.2 on 2025-05-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvitae', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvitae',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
